name: Publish

on:
  push:
    tags:
      - v[0-9]+\.[0-9]+\.[0-9]+
      - v[0-9]+\.[0-9]+\.[0-9]+-next\.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Configure Git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --get user.name
          git config --get user.email

      - name: Setup checkout
        uses: actions/checkout@v5

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup env
        run: |
          tag=$GITHUB_REF_NAME
          version=$(echo $tag | sed -r "s/^v(.*)$/\1/")
          prerelease=false
          if [[ $tag == *"-next"* ]]; then
            prerelease=true
          fi
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          message=$(git tag -l --format='%(contents:subject)' ${GITHUB_REF#refs/tags/})
          if [[ $prerelease == "true" ]]; then
            branch=develop
            tag=next
          else
            branch=master
            tag=latest
          fi

          echo "prerelease=$prerelease" >> $GITHUB_ENV
          echo "version=$version" >> $GITHUB_ENV
          echo "message=$message" >> $GITHUB_ENV
          echo "branch=$branch" >> $GITHUB_ENV
          echo "tag=$tag" >> $GITHUB_ENV

          echo "Prerelease: $prerelease"
          echo "Version: $version"
          echo "Message: $message"
          echo "Branch: $branch"
          echo "Tag: $tag"

      - name: Install
        run: bun i

      - name: Build
        run: bun run build

      - name: Publish
        run: bun publish --tag ${{env.tag}}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{env.version}}
          name: v${{env.version}}
          prerelease: ${{env.prerelease}}
          body: ${{env.message}}
